### ISSUE TITLE
ReadMe example fails?

### ISSUE THREAD

**Issue by iDGS** [brettdewoody/statamic-global-variable-editor#4]
To better compare apples to apples, as they say, I set up the out-of-box Statamic 1.9.2 site in `/Library/WebServer/Documents`, aka where browsers go when you type `localhost` into the URL bar. Only mods I made were to add myself as an Admin, install your add-on per instructions, and a few unrelated trivial changes (+favicon, humans.txt,... stuff I include as reminders of things to do if I want build a brand new site).

Anyway, on that very basic "base," I made the following edit to my `theme.yaml` file, taking it straight out of the ReadMe:

```
global:
  phone: 555-555-5555
  email: you@yourdomain.com
```

Next step: try it out! So, I open the CP, go to the Constants pane, and edit that phone number to instead be`555-555-1212`. Everything works as expected. I also have the `theme.yaml` file open, and I can see it change therein.

Next,... Still in CP, I edit the example email to `my@mysite.com`. But, this time when I click "Save & Publish", I get a surprise: my edit is discarded, `theme.yaml` doesn't change, and my edit is replaced by the previous content, namely `you@yourdomain.com`.

So,... What up with that?

Do you see the same thing under the same circumstances (i.e., running a "bare" Statamic 1.9.2 in localhost, following the install steps, etc.)?

Obviously, I meant all this as a prolog to re-investigating issue #2 , but now I'm not sure what to do.

Please advise?

P.S. I acknowledge it could be just me. Reason I say that: just before this, I installed a bare Statamic 1.10.1, and was going to do my test there, but I couldn't get into the CP. When I tried to log in as Admin under 1.10.1, I just got a totally blank beige page. (I've already let them know; and am awaiting answer...) Go figure. So I git'd back to 1.9.2, and,... there you go.

**Comment by brettdewoody** [comment]
I would not advise having the file open as you make edits in Statamic. I've seen issues with that before. Try it again by only editing the file in the Statamic CP.

**Comment by iDGS** [comment]
OK. I closed the file, logged out of Statamic 1.9.2, quit all programs and rebooted. Then I tried again, without opening the `theme.yaml` or any other file except Firefox: URL: `localhost/admin`. Logged in, tried to edit those two globals. Same thing. Phone yes, email no. It _says_ "Variables updated successfully.", but neh. Only the phone number. The email address gets "reset" to whatever is in the `theme.yaml` file, no matter what I try. (And I did try changing it there. Whatever it is, that's what it stays. Period. Stubborn lil' thing, eh? ;-)

Here's something else I tried. I added a new global:

```
global:
  phone: 555-555-1234
  horoscope: Capricorn
  email: me@mydomain.com
```

and also 

```
global:
  phone: 555-555-1234
  email: me@mydomain.com
  horoscope: Capricorn
```

If you guessed that you can, yes, edit the phone and horoscope, but, no, not the email no matter what the order is, you'd be right!

P.S. I'm not a Capricorn. ;-)

**Comment by brettdewoody** [comment]
Try changing the `email` name to something else like `contact`. So your global array looks like:

```
global:
  phone: 555-555-1234
  contact: me@mydomain.com
  horoscope: Capricorn
```

**Comment by iDGS** [comment]
Good call!  I changed

```
email: me@mydomain.com
```

to

```
contact: me@mydomain.com
```

and it became update-able! (FWIW, I also changed it to `frammistat: me@mydomain.com` and that worked too :-)

I leave it to you to determine what the underlying issue might be, but I would definitely recommend changing that ReadMe example so that it doesn't invite _immediate_ trouble! (Maybe also in the interim include a footnote about there being a "known issue"? Your call.)

Anything else I can help with on this one? Just holler. Meanwhile, I'm heading over to see if I can help muck out that other nearby stall. ;-)

**Comment by brettdewoody** [comment]
No idea why that one variable name would cause problems. Perhaps it's a reserved variable name. 

I updated the README with a new example so this hopefully doesn't happen in the future. Thanks again for all the help.

**Comment by brettdewoody** [comment]
Does PR #3 fix this issue?

**Comment by iDGS** [comment]
I'm sorry--i'm no GitHub ninja, and with distractions and intervening days,
I've become mentally tangled in the various threads of this conversation.

If there's some way for me to help, can you please restate the question?

VTY,
/D

**Comment by brettdewoody** [comment]
You submitted a PR to cleanup the README file and it appeared to have some fixes in the README's sample code that maybe fixed the issue you were having. Is that right?

**Comment by iDGS** [comment]
Yep. The proposed ReadMe tweek helps clarify how things should be installed. Just minor "word-smithing," but such little improvements add up to better UX, right?

However, the suggested re-wording over there has nothing to do with the mystery of why "email" as a global var name is apparently _verbotten_. So, just suggesting that the ReadMe example be repaired to _avoid_ the a head-on collision with that gotcha doesn't mean that the gotcha has been repaired. _That_ would be something I don't think I can help with. 

It's up to you as the developer whether or not you want to chase down that rabbit or not. IMHO "yes, you should," because "email" would seem to be a _very_ likely var name folks might want to use, don'tcha tink? Thus, while you maybe dig in, avoiding mention of it in the docs just _might_ buy you a little time to figure out what's up with that weirdness. Like I said, IMHO. So, like the on-scene newscasters say to the guy back at the station, it's "over to you."

Good luck?

**Comment by brettdewoody** [comment]
Is `email` already being used as a variable? Can you paste your entire `theme.yaml` file?

**Comment by brettdewoody** [comment]
Is `email` already being used as a variable? Can you paste your entire `theme.yaml` file @iDGS?

**Comment by iDGS** [comment]
Don't thing so.

In any case, thanks for your perseverance. Here's the text of the entire `
*theme.yaml*` file:

```
theme_name: basic

# favorite_sites:
#   -
#     name: National Park Service
#     url: http://www.nps.gov/
#   -
#     name: L.L.Bean
#     url: http://llbean.com
#   -
#     name: Statamic
#     url: http://statamic.com
#
# site_twitter: statamic
#
# # used in the feed
site_language: en
# contact_email: you@example.com
#

global:
#`note_re_member_bio`, would also be in /_config/users/member.yaml
  note_re_member_bio_default: <i>[No additional bio notes re <b>{{ username}}</b>.]</i>
#`note_by_admin_to_member`, if there is one, it's in /_config/users/member.yaml
  note_by_admin_to_member_default: <i>[No note from <b>ADMIN</b> to <b>{{username }}</b>.]</i>
  note_by_admin_to_all:
  note_by_admin_to_all_default: <i>[No note from <b>ADMIN</b> to <b>ALL</b>Members.]</i>
#`note_re_member`, if it exists, it's also in /_config/users/member.yaml
  note_re_member_default: <i>[No note from <b>{{ username }}</b> to<b>ALL</b> Members.]</i>
  note_re_dashboard_no_notes_default: <i>[No notes to/from <b>{{ username}}</b> at this time.]</i>
# note_re_privacy_level_public: "" # UNUSED - Public pages have not privacy level indicator
  note_re_privacy_level_private: Only MEMBERS can see some things on this page.
  note_re_privacy_level_personal: Only YOU can see some things on this page.
  note_re_privacy_level_protected: Only ADMINS can see some things on this page.
  show_notes_from_dev_to_admin: 1
  show_warnings_from_dev_to_admin: 1
  show_notes_from_dev_re_pages: 1
  audio_pagination_preference_default: 36
```
